-- Generated by nwg-displays on 2026-09-10 at 23:15:00. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "1920x1080@144.0",
    position = "2880x180",
    scale = 1.5,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1600x900@59.98",
    position = "1280x0",
    scale = 1.0,
    vrr = 0
})
